apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kconnect-cluster
  labels:
    app: kconnect-cluster
spec:
  version: 2.2.1
  replicas: 1
  bootstrapServers: kcluster-kafka-bootstrap:9093
  image: edsa14/mongo-kafka-connect:v2
  authentication:
    type: tls
    certificateAndKey: 
      certificate: user.crt
      key: user.key
      secretName: kafka-connect-user
  tls:
    trustedCertificates:
      - secretName: kcluster-cluster-ca-cert
        certificate: ca.crt
  metrics:
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_connect_metrics_$1_$2"